### ISSUE TITLE
[Docs] : Update contributors to the README.md

### ISSUE THREAD

**Issue by rajgharat07** [nightmare-tech/secure_storage#12]
**Describe the solution you'd like**

## Overview ⭐
I would like to update the profile images of the contributors in the README.md file because I think they appear too small in comparison to the rest of the page and other sections of the README.md.

**Additional context**
### Add Contributor Section 👍 
 - Create a dedicated section in README.md to recognize all contributors to the project. 🏅
 
### List All Current Contributors :
- Add a list or table of contributors with their GitHub profiles or names. This acknowledges their work and provides visibility. 🎖️
 
### Include Contributor Images (Optional) :
- Optionally display GitHub avatars using markdown or a contributors' profile image plugin. 📸

**Comment by nightmare-tech** [comment]
To me the contribution section is already being shown by Github. I dont think this change will bring any value.

**Comment by nightmare-tech** [comment]
![image](https://github.com/user-attachments/assets/ed34fcab-2538-429d-af06-cfe5574b81f8)
