### ISSUE TITLE
Some improvement in the backend

### ISSUE THREAD

**Issue by ritishab0209** [nightmare-tech/secure_storage#4]
I'll make sure passwords are securely hashed with bcrypt instead of MD5, and session management is enhanced with secure cookie settings. Please assign me this task

**Comment by Varun270** [comment]
Hey @ritishab0209 , If you are able to successfully install the cryptography module and  blinker==1.7.0, could you share your pip version with me? Apparently, these modules can't be installed with certain pip versions. I was earlier using pip 24.2 and had to downgrade to pip 20.2.2.
