### ISSUE TITLE
Encryption key is publicly available

### ISSUE THREAD

**Issue by Varun270** [nightmare-tech/secure_storage#7]
The encryption key is included in the normal script which possess a vulnerability. It should be mentioned secretly.

**Comment by Varun270** [comment]
@nightmare-tech I would like to work on this issue!! Kindly assign it to me under hacktoberfest label

**Comment by nightmare-tech** [comment]
Where? What file, line number?

**Comment by Varun270** [comment]
> Where? What file, line number?

I closed this issue as someone already raised a PR fixing this. BTW could you tell me the pip version you are using? As I am not able to download the cryptography and blinker module.
